[versions]
agp = "8.4.1"
androidx-activity = "1.9.0"
androidx-browser = "1.8.0"
androidx-compose-ui-test = "1.7.0-beta01"
androidx-core = "1.13.1"
androidx-core-splashscreen = "1.0.1"
androidx-datastore = "1.1.1"
androidx-material = "1.6.7"
androidx-material3 = "1.2.1"
androidx-palette = "1.0.0"
appauth = "0.11.1"
atomicfu = "0.24.0"
coil = "2.6.0"
compose-bom = "2024.05.00"
compose-constraintlayout = "1.0.1"
compose-runtime = "1.6.7"
coroutines = "1.8.1"
datetime = "0.6.0"
decompose = "3.0.0"
dependency-analysis = "1.32.0"
essenty = "2.0.0"
desugar = "2.0.4"
kenburns = "1.0.7"
kermit = "2.0.3"
kotest = "5.9.0"
kotlin = "2.0.0"
kotlininject = "0.6.3"
kotlinx-collections = "0.3.7"
ksp = "2.0.0-1.0.21"
ktfmt = "0.44"
ktor = "2.3.11"
lint = "1.3.1"
napier = "2.7.1"
paging-multiplatform = "3.3.0-alpha02-0.5.1"
robolectric = "4.12.2"
roborazzi = "1.20.0"
shared-module-version = "0.9.1"
skie = "0.8.2"
snapper = "0.3.0"
sqldelight = "2.0.2"
spotless = "6.25.0"
stately = "2.0.7"
store5 = "5.0.0"
turbine = "1.1.0"
yamlkt = "0.13.0"
youtubePlayer = "12.1.0"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose-ui-test" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-compose-ui-test" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintlayout" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidx-material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-datastore-preference = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette" }

appauth = { module = "net.openid:appauth", version.ref = "appauth" }

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

decompose-decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-extensions-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }
essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

kenburns = { module = "com.flaviofaria:kenburnsview", version.ref = "kenburns" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

kotlinInject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlininject" }
kotlinInject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlininject" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlinx-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

lint-compose = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "lint" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

paging-common = { module = "app.cash.paging:paging-common", version.ref = "paging-multiplatform" }
paging-compose = { module = "app.cash.paging:paging-compose-common", version.ref = "paging-multiplatform" }

robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }

snapper = { module = "dev.chrisbanes.snapper:snapper", version.ref = "snapper" }

sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-primitive-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-paging = { module = "app.cash.sqldelight:androidx-paging3-extensions", version.ref = "sqldelight" }
stately-common = { module = "co.touchlab:stately-common", version.ref = "stately" }
stately-iso-collections = { module = "co.touchlab:stately-iso-collections", version.ref = "stately" }
stately-isolate = { module = "co.touchlab:stately-isolate", version.ref = "stately" }
store5 = { module = "org.mobilenativefoundation.store:store5", version.ref = "store5" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

yamlkt = { module = "net.mamoe.yamlkt:yamlkt", version.ref = "yamlkt" }
youtubePlayer = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "youtubePlayer" }

# Build logic dependencies
android-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
compose-compiler-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
skie = { id = "co.touchlab.skie", version.ref = "skie"}
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

# Project Plugins
tvmaniac-android-library = { id = "plugin.tvmaniac.android.library", version = "unspecified" }
tvmaniac-application = { id = "plugin.tvmaniac.application", version = "unspecified" }
tvmaniac-compose-library = { id = "plugin.tvmaniac.compose.library", version = "unspecified" }
tvmaniac-kotlin-android = { id = "plugin.tvmaniac.kotlin.android", version = "unspecified" }
tvmaniac-multiplatform = { id = "plugin.tvmaniac.multiplatform", version = "unspecified" }

[bundles]
unittest = [
    "coroutines-test",
    "kotest-assertions",
    "turbine",
]
