[versions]
accompanist = "0.28.0"
agp = "8.0.0"
appauth = "0.8.1"

androidx-activity = "1.6.1"
androidx-appCompat = "1.5.1"
androidx-core = "1.9.0"
androidx-datastore = "1.1.0-dev01"
androidx-lifecycle = "2.6.0-alpha05"
androidx-material3 = "1.1.0-alpha06"
androidx-navigation = "2.5.3"
navigation-compose = "1.0.0"
androidx-palette = "1.0.0"
androidx-work = "2.7.1"

coil = "2.2.2"
compileSdk = "33"
compose-bom = "2023.01.00"
composecompiler = "1.4.2"
coroutines = "1.6.4"
dagger = "2.44.2"
desugar = "2.0.2"
junit = "4.13.2"
kotest = "5.5.4"
kotlin = "1.8.0"
kotlininject = "0.6.1"
ktor = "2.1.2"
ksp = "1.8.10-1.0.9"
shared-module-version = "0.6.0"
sqldelight = "2.0.0-alpha05"
turbine = "0.12.1"

[libraries]
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }
android-gradle-tools = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

accompanist-pager-core = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicator = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-insetsui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-runtime = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling"}
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util"}

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }

androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.1" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidx-material3" }
androidx-compose-paging = { module = "androidx.paging:paging-compose", version = "1.0.0-alpha17" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-datastore-preference = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-common = { module = "androidx.navigation:navigation-common", version.ref = "androidx-navigation" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "androidx-navigation" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version = "3.1.1" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

appauth = { module = "net.openid:appauth", version.ref = "appauth" }

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.2" }

flowredux = { module = "com.freeletics.flowredux:flowredux", version = "1.0.2" }

junit = { module = "junit:junit", version.ref = "junit" }

kenburns = { module = "com.flaviofaria:kenburnsview", version = "1.0.7" }
kermit = { module = "co.touchlab:kermit", version = "1.1.3" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

kotlinInject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlininject" }
kotlinInject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlininject" }

ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

lint-compose = { module = "com.slack.lint.compose:compose-lint-checks", version = "1.1.1" }

snapper = { module = "dev.chrisbanes.snapper:snapper", version = "0.3.0" }

sqldelight-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-primitive-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
youtubePlayer = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version = "11.0.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version = "0.7.0" }
dependency-check = { id = "com.github.ben-manes.versions", version = "0.44.0" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.13.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.22.0" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }