[versions]
app-version-code = "1"
app-version-name = "1.0.0"

android-compile = "35"
android-min = "24"
android-target = "35"

jdk = "17"
java-target = "17"
java-toolchain = "23"

ktfmt = "0.44"

agp = "8.10.0"
android-lint = "31.9.2"
androidx-activity = "1.10.1"
androidx-annotation = "1.9.1"
androidx-browser = "1.8.0"
androidx-collections = "1.5.0"
androidx-compose-ui-test = "1.8.0"
androidx-core = "1.16.0"
androidx-core-splashscreen = "1.0.1"
androidx-datastore = "1.1.4"
androidx-material = "1.8.0"
androidx-material3 = "1.3.2"
androidx-palette = "1.0.0"
androidx-paging = "3.3.6"
androidx-savedstate = "1.2.1"
appauth = "0.11.1"
atomicfu = "0.27.0"
baselineprofile = "1.3.4"
benchmarkMacroJunit4 = "1.3.4"
coil = "2.7.0"
compose-bom = "2025.04.01"
compose-constraintlayout = "1.1.1"
compose-runtime = "1.8.0"
coroutines = "1.10.2"
datetime = "0.6.2"
decompose = "3.3.0"
dependency-analysis = "2.15.0"
essenty = "2.5.0"
espressoCore = "3.6.1"
desugar = "2.1.5"
gradle-doctor = "0.10.0"
junit = "1.2.1"
kenburns = "1.0.7"
kermit = "2.0.5"
kotest = "5.9.1"
kotlin = "2.1.20"
kotlininject = "0.8.0"
kotlin-inject-anvil = "0.1.4"
kotlinx-collections = "0.3.8"
ksp = "2.1.20-2.0.0"
ktor = "3.1.2"
lint = "1.4.2"
napier = "2.7.1"
robolectric = "4.14.1"
roborazzi = "1.43.1"
profileinstaller = "1.4.1"
serialization = "1.8.1"
skie = "0.10.2-preview.2.1.20"
snapper = "0.3.0"
sqldelight = "2.0.2"
spotless = "7.0.3"
store5 = "5.0.0"
turbine = "1.2.0"
uiautomator = "2.3.0"
yamlkt = "0.13.0"
youtubePlayer = "12.1.1"

[libraries]
android-lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "android-lint" }
android-lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "android-lint" }
android-lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "android-lint" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose-ui-test" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-compose-ui-test" }
androidx-collections = { group = "androidx.collection", name = "collection", version.ref = "androidx-collections" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintlayout" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidx-material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
androidx-core-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-datastore-preference = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "androidx-palette" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "androidx-paging" }
androidx-savedstate = { group = "androidx.savedstate", name = "savedstate", version.ref = "androidx-savedstate" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }

appauth = { module = "net.openid:appauth", version.ref = "appauth" }

baselineprofile-gradlePlugin = { group = "androidx.benchmark", name = "benchmark-baseline-profile-gradle-plugin", version.ref = "baselineprofile" }
coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

decompose-decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-extensions-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }
essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

kenburns = { module = "com.flaviofaria:kenburnsview", version.ref = "kenburns" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

kotlinInject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlininject" }
kotlinInject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlininject" }
kotlinInject-anvil-compiler = { group = "software.amazon.lastmile.kotlin.inject.anvil", name = "compiler", version.ref = "kotlin-inject-anvil" }
kotlinInject-anvil-runtime = { group = "software.amazon.lastmile.kotlin.inject.anvil", name = "runtime", version.ref = "kotlin-inject-anvil" }
kotlinInject-anvil-runtime-optional = { group = "software.amazon.lastmile.kotlin.inject.anvil", name = "runtime-optional", version.ref = "kotlin-inject-anvil" }

kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlinx-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

lint-compose = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "lint" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }

snapper = { module = "dev.chrisbanes.snapper:snapper", version.ref = "snapper" }
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-primitive-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
store5 = { module = "org.mobilenativefoundation.store:store5", version.ref = "store5" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

yamlkt = { module = "net.mamoe.yamlkt:yamlkt", version.ref = "yamlkt" }
youtubePlayer = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "youtubePlayer" }

# Build logic dependencies
android-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
dependency-analysis-gradle-plugin = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependency-analysis" }
gradle-doctor-gradle-plugin = { group = "com.osacky.doctor", name = "doctor-plugin", version.ref = "gradle-doctor" }
skie-gradle-plugin = { module = "co.touchlab.skie:gradle-plugin", version = "0.10.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

# Project Plugins
tvmaniac-application = { id = "com.thomaskioko.tvmaniac.gradle.app" }
tvmaniac-android = { id = "com.thomaskioko.tvmaniac.gradle.android" }
tvmaniac-baseline-profile = { id = "com.thomaskioko.tvmaniac.gradle.baseline.profile" }
tvmaniac-kmp = { id = "com.thomaskioko.tvmaniac.gradle.multiplatform" }
tvmaniac-spotless = { id = "com.thomaskioko.tvmaniac.gradle.spotless" }
tvmaniac-root = { id = "com.thomaskioko.tvmaniac.gradle.root" }

[bundles]
kotlinInject = [
  "kotlinInject-runtime",
  "kotlinInject-anvil-runtime",
  "kotlinInject-anvil-runtime-optional"
]
unittest = [
  "coroutines-test",
  "kotest-assertions",
  "kotlin-test",
  "turbine",
]

lint = [
  "android-lint-api",
  "android-lint-checks",
  "android-lint-tests"
]
