[versions]
kotlin = "1.6.10"

android-compile = "31"
android-target = "31"
android-min = "23"

android-gradle = "7.2.0"
date-time = "0.3.2"

accompanist = "0.24.6-alpha"
snapper = "0.2.0"

androidx-activity = "1.4.0"
androidx-appCompat = "1.4.0"
androidx-core = "1.9.0-alpha02"
androidx-compose = "1.2.0-alpha07"
compose-compiler = "1.2.0-alpha07"
androidx-composePaging = "1.0.0-alpha14"
androidx-constraintlayout = "1.0.0"
androidx-datastore = "1.0.0"
androidx-lifecycle = "2.5.0-alpha06"
androidx-navigation = "2.5.0-alpha04"
androidx-palette = "1.0.0"
androidx-paging = "3.1.0"

coil = "1.4.0"
coroutines = "1.6.1"
dagger = "2.41"
desugar = "1.1.5"
hilt = "2.41"
hiltNavigation = "1.0.0"
inject = "1"
kenburns = "1.0.7"
kermit = "1.0.3"
koin = "3.2.0"
ktor = "1.6.7"
material = "1.6.0-alpha01"
multiplatform-paging = "0.4.7"
squareup-leakcanary = "2.8.1"
sqldelight = "1.5.3"
turbine = "0.7.0"

testing-arch-core = "2.1.0"
testing-junit = "4.13.2"
testing-junitext = "1.1.4-alpha05"
testing-junit5 = "5.8.2"
testing-kotest = "5.2.3"
testing-mockk = "1.12.3"
testing-mockito-kotlin = "2.2.0"

plugin-buildkonfig = "0.7.0"
plugin-gradle-versions = "0.39.0"
plugin-detekt = "1.19.0"

shared-module-version = "0.5.0"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "date-time" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }

accompanist-pager-core = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicator = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-insetsui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette" }

androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
androidx-compose-ui-runtime = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "androidx-compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-compose-paging = { module = "androidx.paging:paging-compose", version.ref = "androidx-composePaging" }

androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }

androidx-navigation-common = { module = "androidx.navigation:navigation-common-ktx", version.ref = "androidx-navigation" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "androidx-navigation" }

androidx-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }

inject = { module = "javax.inject:javax.inject", version.ref = "inject" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
kenburns = { module = "com.flaviofaria:kenburnsview", version.ref = "kenburns" }
snapper = { module = "dev.chrisbanes.snapper:snapper", version.ref = "snapper" }

multiplatform-paging-core = { module = "io.github.kuuuurt:multiplatform-paging", version.ref = "multiplatform-paging" }
multiplatform-paging-ios-x64 = { module = "io.github.kuuuurt:multiplatform-paging-iosX64", version.ref = "multiplatform-paging" }
multiplatform-paging-ios-arm64 = { module = "io.github.kuuuurt:multiplatform-paging-iosArm64", version.ref = "multiplatform-paging" }

squareup-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "squareup-leakcanary" }
squareup-sqldelight-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
squareup-sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelight" }
squareup-sqldelight-driver-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
squareup-sqldelight-driver-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
squareup-sqldelight-driver-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqldelight" }

plugin-dependency-check = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "plugin-gradle-versions" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
plugin-buildkonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "plugin-buildkonfig" }
plugin-squareup-sqldelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "plugin-detekt" }

testing-androidx-core = { module = "androidx.arch.core:core-testing", version.ref = "testing-arch-core" }
testing-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "testing-junitext" }

testing-junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "testing-junit5" }
testing-junit5-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "testing-junit5" }
testing-junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "testing-junit5" }

testing-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "testing-kotest" }
testing-kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "testing-kotest" }

testing-mockk-core = { module = "io.mockk:mockk", version.ref = "testing-mockk" }
testing-mockk-common = { module = "io.mockk:mockk-common", version.ref = "testing-mockk" }

testing-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
testing-junit = { module = "junit:junit", version.ref = "testing-junit" }
testing-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

testing-ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
